### ISSUE TITLE
getting started page forgets to commit the results

### ISSUE THREAD

**Issue by tve** [constabulary/getgb.io#18]
The getting started page http://getgb.io/examples/getting-started/ has a number of interesting examples in the "converting an existing project" section where it uses `git clone` to populate the vendor/src directory. However, the examples stop at building the result and don't show how to commit the whole project in the end back into a git repo. A simple `git add .; git commit` doesn't work because the result would be that the repo would have a bunch of submodules for everything that was git cloned into vendor/src, which defeats part of the whole vendoring. Is one supposed to run `rm -rf $(find vendor/src -name .git)` before the `git add`? That loses all info about where the sources came from ... I know that some of this is "beyond the scope of gb" but not talking about it in the examples makes new users stumble and wonder whether this gb thing really works... (Not trying to bash gb, I'm thankful for you trying to wrangle the beast down!)

**Comment by davecheney** [comment]
This is a deliberate choice. gb does not dictate what source control you
should use for your project, at the moment this requires some level of
maturity from the project owner

**Comment by tve** [comment]
I understand the "out of scope" comment, but at the same time your example sets the reader up for failure. When I arrived at the `git add .` step after having gone through your example and wanted to commit my result I got reminded that git doesn't actually add anything with a .git subdirectory in it a red flag went up: "is this gb thing really thought through?" and "ok, now what? If I just `rm -rf` the .git subdirectory I have no record of what revision I vendored nor any convenient way to update it". At that point I was pretty much stranded. Please don't take this as an offence, just as what went through my mind.

**Comment by davecheney** [comment]
> Please don't take this as an offence, just as what went through my mind.

No offense taken. gb is still very new, and this is one of the unfortunate
rough edges at the moment.

The truth is that all of this will have to be replaced with a new version
of the gb-vendor plugin which should manage collecting, recording, and
updating dependencies for you.

**Comment by davecheney** [comment]
I'm going to mark this as closed as we have gb-vendor, and i've written and spoken about it a fair bit. http://dave.cheney.net/2015/06/09/gb-a-project-based-build-tool-for-the-go-programming-language
